version: "3.8"

services:

  #base de datos de keycloack
  postgres-keycloak:
    image: postgres:16
    container_name: postgres-gym-keycloak
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak_pass
    volumes:
      - ./keycloak-data:/var/lib/postgresql/data
    networks:
      - Booking-network

  #servicio de keycloack
  keycloak:
    image: quay.io/keycloak/keycloak:25.0
    container_name: keycloak-gym
    command:
      - start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres-keycloak:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak_pass
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8180:8080"
    depends_on:
      - postgres-keycloak
    networks:
      - Booking-network

#base de datos servicio ClassBooking
  postgrest-ClassBooking:
    image: postgres:16
    container_name: postgres-ClassBooking
    environment:
      POSTGRES_DB: ClassBooking_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Uisrael.
    ports:
      - "5433:5432"
    networks:
      - Booking-network


  classbooking-service:
    build:
      context: ./ClassBooking-service
      dockerfile: Dockerfile
    container_name: classbooking-service
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgrest-ClassBooking:5432/ClassBooking_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Uisrael.
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://keycloak:8080/realms/gym-system
    depends_on:
      - postgrest-ClassBooking
      - keycloak
    networks:
      - Booking-network


networks:
  Booking-network:
    driver: bridge
