events {
    worker_connections 1024;
}

http {

    server {
        listen 80;

        # Reenvia las peticiones de /api/ hacia el microservicio classbooking-service
        # que ahora corre dentro de Docker, en la red Booking-network, puerto 8081
        location /api/ {
            proxy_pass http://classbooking-service:8081/api/;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            # Preserva el header Authorization sin modificarlo
            proxy_pass_header Authorization;
        }
    }
}
